name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # - macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        if: runner.os != 'Windows'
      - uses: jiro4989/setup-nim-action@v1
      - run: nimble build -d:release -Y
      - run: nimble install -Y
      - run: nim_ci_sample 10
      - run: nimble doc --project --index:on -o:docs src/nim_ci_sample.nim
      - name: Create artifact
        run: tar czf nim_ci_sample_${{ runner.os }}.tar.gz README.md nim_ci_sample
      - name: Release binary
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: nim_ci_sample*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}